# Stage 1
FROM node:20-alpine AS builder

ARG API_BASE_URL
ARG FILE_BASE_URL
ARG SOCKET_URL
ARG RecaptchaSiteKey
ENV API_BASE_URL=${API_BASE_URL}
ENV FILE_BASE_URL=${FILE_BASE_URL}
ENV SOCKET_URL=${SOCKET_URL}
ENV RecaptchaSiteKey=${RecaptchaSiteKey}

WORKDIR /usr/app
RUN apk add --no-cache python3 make g++ && ln -sf python3 /usr/bin/python
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

# Install Dependencies
RUN npm ci --legacy-peer-deps


COPY ./ .

# Build
RUN npm run build --prod

# Stage 2
FROM nginx:1.27-alpine

COPY --from=builder /usr/app/dist /usr/share/nginx/html